networks:
  default-network:
    driver: bridge

volumes:
  webpage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /d/workspace/git/docker-docusaurus/test-folder
 
services:
  my-webpage-sample:
    image: scisoftware/docusaurus:10.9.2
    networks:
      - default-network
    environment:
      - WORKSPACE_NAME=public	  
    volumes: 
      - webpage:/webdir/public
    ports:
      - "3000:3000"
